### ISSUE TITLE
Improve dependency scanner by passing GITHUB_TOKEN

### ISSUE THREAD

**Issue by prabhu** [drakeg/drakeweb#19]
Thank you for using scan :) By simply passing the github token, you can improve the dependency scan results.

https://docs.shiftleft.io/shiftleft/scan/integrations/github-actions

```yaml
- name: ShiftLeft Scan
  uses: ShiftLeftSecurity/scan-action@master
  env:
    WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    output: reports
- name: Upload scan reports
  uses: actions/upload-artifact@v1.0.0
  with:
    name: shiftleft-scan-reports
    path: reports
```

Hope this helps.
